ARITHMETIC OPERATIONS

In [2]:
import numpy as np

In [5]:
a1=np.array([1,2,3,4,5]) # arrays with same number of elements
a2=np.array([6,7,8,9,10])

In [7]:
a1+a2 #two add the elements of both the arrays
#What if the number of elements are not same? It'll throw error, therefore  array sizes must be same forr operations to be performed.

array([ 7,  9, 11, 13, 15])

In [8]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
a1//a2

array([0, 0, 0, 0, 0])

In [10]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

BROADCASTING

In [3]:
l=[10,20,30,40]
arr=np.array(l)

In [5]:
arr + 10 # when we want to add a single value to every element that is what we call broadcasting.

array([20, 30, 40, 50])

In [8]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
arr2 +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

DEEP AND SHALLOW COPY

In [11]:
a =np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5] # sliced out a portion from the array a.
slice = slice*10 # Did broadcasting in the sliced portion.
slice # printed the sliced array to see the result.

array([10, 20, 30, 40, 50])

In [ ]:
a # But even after slicing the original array remains unaffected, it is still the same.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# SHALLOW copy is when even after making changes to the sliced portion the orriginal array remains same because it creates a different copy or has a different space
# for sliced portion in RAM/Memory unlike list where the original list used to get affected.

In [18]:
a[4:6]*10

array([50, 60])

In [20]:
a  #Still the same in orginal array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a
b=a

In [24]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a # now a original array is changed because we changed b. Because when we say a=b they share the same location in memory. Therefore changes made in a are reflected in b.
  # This is called as DEEP copy.

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# if we do not want changes made in b to get reflected in a and want a and b to be the same, we use its copy.
b=a.copy()
b[2]=-25
b  # index 2 of b is changes to -25.

array([ 99,   2, -25,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [31]:
a # remains same, therefore a shallow copy.

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])