In [2]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [6]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[9]  #This will print the element at 9th index. This is INDEXING.

np.int64(20)

In [ ]:
# SLICING is take out a portion from an array.
arr[1:5] #This will give elemts from index 1 to n-1 that is 4 (5-1) in this case.

array([12, 13, 14, 15])

In [9]:
arr[:5] # Starting index is 0 by default.

array([11, 12, 13, 14, 15])

In [10]:
arr[3:] # end is by default the last index of the array.

array([14, 15, 16, 17, 18, 19, 20])

In [15]:
arr_slice=arr[1:8:2] # this slices elements form index 1 to 8 at a gap of 1, say its taking jump of one.
arr_slice # sliced array can nbe stored in diff vatiable and perform further operations.

array([12, 14, 16, 18])