In [2]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [6]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[9]  #This will print the element at 9th index. This is INDEXING.

np.int64(20)

In [ ]:
# SLICING is take out a portion from an array.
arr[1:5] #This will give elemts from index 1 to n-1 that is 4 (5-1) in this case.

array([12, 13, 14, 15])

In [9]:
arr[:5] # Starting index is 0 by default.

array([11, 12, 13, 14, 15])

In [10]:
arr[3:] # end is by default the last index of the array.

array([14, 15, 16, 17, 18, 19, 20])

In [15]:
arr_slice=arr[1:8:2] # this slices elements form index 1 to 8 at a gap of 1, say its taking jump of one.
arr_slice # sliced array can nbe stored in diff vatiable and perform further operations.

array([12, 14, 16, 18])

NUMPY INDEXING AND SLICING OF MATRIX

In [4]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5]  # to print a row

array([26, 27, 28, 29, 30])

In [8]:
arr[0,0] # to print a particular element.

np.int64(1)

In [ ]:
arr[0:2,1:3]  # to slice out some portion, 0:2 for row from 0 to 1 and 1:3 is for the column from 1 to 2. 

array([[2, 3],
       [7, 8]])

In [11]:
#Similarly
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
#to slice out the column, entire row has to be selected and desired column.
arr[:,2]
#It gives 

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [19]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
bool_index=arr%2==0  
bool_index  #This will show true in place of the values that are divisible by 2 and falso otherwise.

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr=arr[bool_index] # This will store the array having only the true values in arr. Al the false values are removed
arr

array([12, 14, 16, 18, 20])