In [1]:
import numpy as np
import pandas as pd

In [ ]:
arr=np.array([1,2,3,4]) #Can only store data of only a single data type.
arr

array([1, 2, 3, 4])

In [9]:
a = [1,2,3,4,"Hello"]  #a simple array. Can store data of multiple data types.
a

[1, 2, 3, 4, 'Hello']

In [11]:
np.array(a) #since array can only store a single data type's data. It gives an output U21 that indicates everything is converted in string.

array(['1', '2', '3', '4', 'Hello'], dtype='<U21')

In [ ]:
l = [[1,2,3],[2,3,4],[4,5,6]]  # A list will create a one dimensional output. Also known as vector.
l

[[1, 2, 3], [2, 3, 4], [4, 5, 6]]

In [15]:
np.array(l)  #But as soon as we convert it into an array it gives a two dimensional output. Also known as matrix.

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [16]:
# Same way we have 3 dim, 4 dim and so on. All above 2D are called tensors that we'll learn further.

In [20]:
b=np.arange(1,11)
b #will create array from 1 to n-1 that is in this case 10 (11-1).

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b=np.zeros(6) #creates a vector with 6 zeroes.
b

array([0., 0., 0., 0., 0., 0.])

In [27]:
b=np.zeros((6,6)) #matrix with zeroes in 6 rows and 6 columns.
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
b=np.ones((4,8)) #Matrix with all values 1 in 4 rows and 8 columns.
b

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
b=np.linspace(1,5,100) #Returns evenly spaced numbers over a specified element.
b

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [ ]:
np.random.rand(5) #generates and prints 5 random number on vector form between the range of zero and one (Concept of normalisation).

array([0.04893896, 0.75013816, 0.77273491, 0.01533722, 0.67013141])

In [4]:
np.random.randn(10) # generates values between -3 ansd 3 which is a concept of normalisation.

array([ 0.0576818 ,  0.48290944, -2.07531573,  0.21237904,  1.27336297,
       -0.49656634,  0.83050189, -2.00025364, -1.60439136, -0.15544448])

In [8]:
np.random.randint(6) # Generates any integer randomly between 0 to 6.
np.random.randint(10,20) # Generates any random int between 10 and 30.
np.random.randint(10,20,7) #Generate 7 random integers between 10 and 20.

array([13, 14, 15, 11, 11, 16, 12], dtype=int32)

In [10]:
np.random.randint(20,30,20) 

array([28, 24, 22, 26, 23, 24, 25, 23, 27, 21, 21, 23, 27, 23, 29, 25, 26,
       21, 25, 28], dtype=int32)

ARRAY ATTRIBUTES

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
arr.shape  # shape shows the no. of rows and columns. But since it is an atrribute we do not
           # need parentheses () in front of them to execute. It will thow an error.

(3, 3)

In [20]:
arr.size  #total number of elements

9

In [21]:
arr.dtype  #data type of the variable.

dtype('int64')

ARRAY METHODS

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
arr.min()  # min,max,sum,... all these are array attributes therefore we need to give parentheses () in order for them to execute.

np.int64(1)

In [24]:
arr.max()

np.int64(8)

In [ ]:
arr.sum() #sum is in built function of python. But numpy provides one more function np.sum, that does the following given in next cell.

np.int64(42)

In [30]:
np.sum(arr,axis=0) # If column wise sum is needed, keep axis=0. For row wise keep axis =1.

array([11, 14, 17])

In [33]:
np.sum(arr,axis=1)  #row wise sum.

array([ 6, 15, 21])

In [ ]:
arr.mean() # Tells the mean value.

np.float64(4.666666666666667)